#!/usr/bin/env bash
# Script to install engine x

sudo apt-get update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
sudo echo "Hello World!" > /var/www/html/index.html
sudo service nginx start
