#!/usr/bin/env bash
# Script to install engine x

sudo apt-get update
sudo apt-get install -y nginx
sudo echo "<html><body><h2>Hello World!</h2></body></html>" > /var/www/html/index.html
sudo echo "server {
listen 80 default_sver;
listen [::]:80 default_server;
root /var/www/html;
index index.html;
server_name _;
location / {
	try_files \$uri \$uri/ =404;
}
}" > /etc/nginx/sites-available/default
sudo service nginx restart
