#!/usr/bin/env bash
# Script that configures a new Ubuntu machine.

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i 'server_name _;/a \\\trewrite ^/redirect_me https://medium.com/@calebzwingli permanent;' /etc/nginx/sites-enabled/default

sudo service nginx restart
