#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to match the task requirements

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i '/server_name _;/a \\\trewrite ^/redirect_me https://www.blog.ehoneahobed.com permanent;' /etc/nginx/sites-available/default

sudo tee /var/www/html/404.html <<EOT
<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <center><h1>404 Not Found</h1></center>
    <hr>
    <center>Ceci n'est pas une page.</center>
    <hr>
    <center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
EOT

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

sudo service nginx restart

