#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo sed -i '/server_name _;/a \\\trewrite ^/redirect_me https://www.blog.ehoneahobed.com permanent;' /etc/nginx/sites-enabled/default

sudo sed -i '/listen 80 default_server;/a \\\n\terror_page 404 /404.html;' /etc/nginx/sites-enabled/default

sudo tee /var/www/html/404.html <<EOT
<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>404 Not Found</h1>
    <p>Ceci n'est pas une page.</p>
</body>
</html>
EOT

sudo service nginx restart
