#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configuration on HAProxy should send traffic to web-01 and web-02 servers

sudo apt-get -y update
sudo apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  zwart-frontend
        bind *:80
        mode http
        default_backend zwart_backend
backend zwart-backend
        balance roundrobin
        server 165722-web-01 54.237.116.139:80 check
        server 165722-web-02 34.207.212.66:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
