#!/usr/bin/env bash
# A script that displays 1 to 100

#a fizbuzz is displayed when number is a multiple of 3 and 5
# if not display the number in a list format

for i in $(seq 1 100)
do
	if [ $((i % 15)) -eq 0 ]; then
		echo "FizzBuzz"
	elif [ $((i % 5)) -eq 0 ]; then
		echo "Buzz"
	elif [ $((i % 3)) -eq 0 ]; then
		echo "Fizz"
	else
		echo "$i"
	fi
done
