#!/usr/bin/env bash
# A bash script that displays the content of the file /etc/passwd.
# Your script should only display
# username, user id, home directory path for user

while IFS= read -r lines;
do
	echo "$lines" | cut -d':' -f1,4,7
done < /etc/passwd
