#!/usr/bin/env bash
# A bash script that groups visitors by IP and HTTP status code and displays the data

# Displays the number of occurrences as well

awk '{ print $1," " $9 }' apache-access.log | sort | uniq -c | sort -rn
