#!/usr/bin/env bash
# A bash  script displaying 1 to 20
# displays 4 and then bad luck from china for 4th iteration
# display 9 then bad luck from Japan for the 9th loop iteration
# displays 17 and then  bad luck fro italy for the iteration

i=1;

while ((i < 21))
do
	echo "$i"
	case "$i" in 4)
			echo "bad luck from China";;
			9)
			echo "bad luck from Japan";;
			17)
			echo "bad luck from Italy";;
	esac
	((i++))
done
