#!/usr/bin/env bash
# A bash script that displays the time for 12hrs and 59 minutes; 
#displays 1 to 12 and 1 to 59

#

hours=0;

while ((hours < 13))
do
	echo "Hour: $hours"
	minutes=1;
	while ((minutes < 60))
	do
		echo "$minutes"
		((minutes++))
	done
	((hours++))
done
