#!/usr/bin/env bash
# A bash script that configures an ubuntu server where:
# localhodt resolves to 127.0.0.2
# facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.cpy
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.cpy
cp -f ~/hosts.cpy /etc/hosts
